spring.config.activate.on-profile=nacos
spring.config.import=optional:nacos:booking-system.properties?refreshEnabled=true

spring.cloud.nacos.discovery.enabled=true
spring.cloud.nacos.discovery.server-addr=${NACOS_SERVER_ADDR:127.0.0.1:8848}
spring.cloud.nacos.discovery.namespace=${NACOS_NAMESPACE:public}
spring.cloud.nacos.discovery.group=${NACOS_GROUP:DEFAULT_GROUP}
spring.cloud.nacos.discovery.username=${NACOS_USERNAME:}
spring.cloud.nacos.discovery.password=${NACOS_PASSWORD:}
spring.cloud.nacos.discovery.register-enabled=true
spring.cloud.nacos.discovery.ephemeral=true
spring.cloud.nacos.discovery.watch.enabled=true
spring.cloud.nacos.discovery.metadata.context-path=${server.servlet.context-path}

spring.cloud.nacos.config.server-addr=${NACOS_SERVER_ADDR:127.0.0.1:8848}
spring.cloud.nacos.config.namespace=${NACOS_NAMESPACE:public}
spring.cloud.nacos.config.group=${NACOS_GROUP:DEFAULT_GROUP}
spring.cloud.nacos.config.username=${NACOS_USERNAME:}
spring.cloud.nacos.config.password=${NACOS_PASSWORD:}
spring.cloud.nacos.config.refresh-enabled=true
